with open('backend.py', 'r', encoding='utf-8', errors='ignore') as f:
    content = f.read()

# The backward search sets both confirmed_period AND overwrites strong_pair
# We need to keep confirmed_period but remove the strong_pair overwrite
# In the compact format, it looks like:
#   confirmed_period = issue_numbers[i+1]; break

# Find and remove lines that set strong_pair in the backward search
# The backward search pattern in backend.py (compact form):
old1 = '            confirmed_period = issue_numbers[i+1]; break'
# This should be fine as-is since it doesn't set strong_pair

# Check if there's a strong_pair overwrite in the backward search
# The backend.py was generated by the repair script, so let's check
lines = content.split('\n')
new_lines = []
in_backward_search = False
for i, line in enumerate(lines):
    # Don't modify - the repair script version doesn't have the overwrite
    new_lines.append(line)

# Actually, let me just check if the issue exists
if 'strong_pair = (issue_numbers[i], issue_numbers[i+1])' in content:
    content = content.replace(
        '            strong_pair = (issue_numbers[i], issue_numbers[i+1])\n            confirmed_period = issue_numbers[i+1]; break',
        '            confirmed_period = issue_numbers[i+1]; break'
    )
    with open('backend.py', 'w', encoding='utf-8') as f:
        f.write(content)
    print("Patched backend.py - removed strong_pair overwrite")
else:
    print("backend.py already correct - no strong_pair overwrite found in backward search")
